config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }


  root "homes#top"
  get "/home/about"=>"homes#about"
  resources:users
  resources:books

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user, optional:true

  attachment :profile_image
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  
  attachment :profile_image

  validates :name, uniqueness: true,length: {in: 2..20}
  validates :introduction,length: { maximum: 50}


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters,if: :devise_controller?
  before_action :authenticate_user!,except:[:top,:about,:public_action]
  
    def after_sign_out_path_for(resource)
      root_path
    end

    def after_sign_in_path_for(resource)
      user_path(resource.id)
    end  
    
    
  
  
  protected
    def configure_permitted_parameters
        if resource_class == User
            devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
            devise_parameter_sanitizer.permit(:sign_in,keys:[:email])
            devise_parameter_sanitizer.permit(:account_update,keys:[:name,:email])
        end
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def show
    @newbook=Book.new
    @book=Book.find(params[:id])
    @user=@book.user
  end

  def index
    @user=current_user
    @book=Book.new
    @books=Book.all
  end

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save

      flash[:notice]="You have creatad book successfully."
      redirect_to book_path(@book)
    else
      @books=Book.all
      render "index"
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice]="Book was successfully destroyed."
      redirect_to books_path
    end
  end


    private
    def book_params
      params.require(:book).permit(:title, :body)
    end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = Book.where(user_id: @user.id)
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all    
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice]="You have updated user successfully."
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
 
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.erb
<%= form_with( model:book,local: true) do |f| %>
  <div class="form-group row">
    <%= f.label :Title %>
    <%= f.text_field :title, class: "form-control col-xs-12" %>
  </div>

  <div class="form-group row">
  	<%= f.label :Body %>
    <%= f.text_area :body, class: "form-control col-xs-12" %>
  </div>

  <div class="actions row">
    <%= f.submit class: "btn btn-success col-xs-12" %>
  </div>
<% end %>

app/views/books/_error.html.erb
<% if model.errors.any? %>
  <div class="error">
    <h3><%= model.errors.count %> errors prohibited this obj from being saved</h3>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
          <% if @book.errors.any? %>
            <div class="error">
              <h3><%= @book.errors.count %> errors prohibited this obj from being saved</h3>
              <ul>
                <% @book.errors.full_messages.each do |message| %>
                  <li class="error-message"><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <%= render 'books/book', book:@book %>
        <div class="menu">
          <%= link_to "Show", book_path(@book) %>
          |
          <%= link_to "Back", books_path %>
        </div>
        </div>
      <div class="col-xs-3"></div>
    </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
    <div>
      <%= render 'books/error',model:@book %>
    </div>
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user',user:current_user %>
      <h2 calss="mt-3">New book</h2>
      <%= render 'books/book',book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <table class="table table-hover table-inverse">
        <h2>Books</h2>
        <thead>
          <tr>
            <th></th>
            <th>Title </th>
            <th>Option</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill,40,40,fallback:"no_image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to book.title,book_path(book.id) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>

</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/book', book: @newbook %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-user-show">
        <tr>
          <td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg"%></td>
          <td><%= link_to @user.name, user_path(@user) %></td>
          <td><%= @book.title %></td>
          <td><%= @book.body %></td>
          <% if @book.user_id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-success"%></td>
            <td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-danger" %></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcom to
      <i class="fas fa-book"::before></i>
      <strong>Bookers</strong>
      !
    </h1>
    
  </div>
  
</div>

app/views/homes/top.html.erb
<div class="container">
  <div clas="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      
      <div class="top-text">
        <h1>
          Welcom to
          <span class="fas fa-book"::before></span>
          <b>Bookers!!</b>
        </h1>
        
        <p>
          In
          <apan class="fas fa-book"::before></apan>
          <b>Bookers</b>,<br>
          you can share and exchange your opinions , inpresiions , and emotions<br>
		  	  about various books!          
        </p>
      </div>
      
      <div clss="btn-wapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log In",new_user_session_path,class:"btn btn-info btn-sm stn-block mb-3 sign_in" %>
        </div>
        
        <div class="row">
          <%= link_to "Sign Up",new_user_registration_path,class:"btn btn-success btn-sm bstn-block sign_up" %>
        </div>
      </div>
      
    </div>
    
  </div>
    
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/c25d5dc5a9.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header> 
      <nav class="navbar nabvbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-band" href="/">
            <span class="title">Bookers</span>
          </a>

            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="">
                  <%= link_to user_path(current_user),class:"btn btn-link" do %>
                    <span class="fas fa-home nav-link text-light"::before> Home</span>
                  <% end %>
                </li>
                
                <li class="">
                  <%= link_to users_path,class:"btn btn-link" do %>
                    <span class="fas fa-users nav-link text-light"::before>Users</span>
                  <% end %>
                </li>
                
                <li class="">
                  <%= link_to books_path,class:"btn btn-link" do %>
                    <span class="fas fa-book-open nav-link text-light"::before>Books</span>
                  <% end %>
                </li>       
                
                <li class="">
                  <%= link_to destroy_user_session_path,method: :delete ,class:"btn btn-link" do %>
                    <span class="fas fa-sign-out-alt nav-link text-light"::before>logout</span>
                  <% end %>
                </li>    
                
              <% else %>
                <li class="">
                  <%= link_to "/",class:"btn btn-link" do %>
                    <span class="fas fa-home nav-link text-light"::before="true">Home</span>
                  <% end %>
                </li>
                
                <li class="">
                  <%= link_to home_about_path,class:"btn btn-link" do %>
                    <span class="fas fa-link nav-link text-light"::before>About</span>
                  <% end %>
                </li>
                
                <li class="">
                  <%= link_to new_user_registration_path,class:"btn btn-link" do %>
                    <span class="fas fa-user-plus nav-link text-light"::before>sign up</span>
                  <% end %>
                </li>
                
                <li class="">
                  <%= link_to new_user_session_path,class:"btn btn-link" do %>
                    <span class="fas fa-sign-in-alt nav-link text-light"::before>Login</span>
                  <% end %>
                </li>              
              <% end %>
            </ul>

        </div>
      </nav>
    </header>
    <div class="body">
      <p class="notice"><%= notice %></p>

      <%= yield %>


        <footer>
          <div class="container mt-5">
            <div class="row">
              <div class="mx-auto">
                <p>CopyRight Infratop.inc</p>
              </div>
            </div>
          </div>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/users/_user.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col">
      <table class="table table-user">
        <h2>User info</h2>
        <thead>
          <tr>
            <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format:'jpeg', fallback: "no_image.jpg"%>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>Name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>Introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" do %>
        <% end %>    
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div clss="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= form_for(@user) do |f| %>
      <%= render 'books/error', model:@user %>
        <div class="form-group">
          <div class="user-name">Name</div>
            <%= f.text_field :name ,class:"form-control name" %>          
        </div>
        <div class="form-group">
          <div class="user-edit-image">Image</div>
            <%= f.attachment_field :profile_image ,class:"form-control-file user_image" %>
        </div>
        <div class="form-group">
          <div class="form-body">Introduction</div>
            <%= f.text_area :introduction ,class:"form-control introduction" %><br>          
        </div>
        <div class="form-group">
            <%= f.submit "Update User", class:"btn btn-secondary" do%>
            <% end %>
        </div>
      <% end %>      
      
    </div>
    
  </div>
  
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user:@user %>
      <h2>New book</h2>
      <%= render 'books/book', book:@book %>
    </div>
    <div class="col-md-8 offset-md-1">
  	  <table class="table table-sm user-index">
	  	  <h2>Users</h2>
        <thead>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
  	    </thead>
  	  	<tbody>
  	  	  <% @users.each do |user| %>
	  	  	<tr>
	  	  	  <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40,fallback: "no_image.jpg"%></td>
	  	  	  <td><%= user.name %></td>
	  	  	  <td><%= link_to "Show", "/users/#{user.id}" %></td>
	  	  	</tr>
  	  	  <% end %>
  	  	</tbody>
  	  </table>
  	</div>
  </div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-user-show">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Option</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(@user) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg"%>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>